% koto_shussan_oiwaikin.pl - koto ward childcare/birth support program
% VERIFIED 2026-06-15. Subject: child. FY-end age <= 1.
% Amount: 50000 JPY (oneoff).
% Generated by scripts/gen_ward_kosodate_ouen.py.
% Requires engine.pl.

:- module(koto_shussan_oiwaikin, [kettei_status/3, required_fact/3]).

required_fact(_, _, _) :- fail.

kettei_status(P, C, error(structural_facts_missing)) :-
    claimant(P), child(C), \+ age_nendo_matsu(C, _), !.
kettei_status(P, C, ineligible(age_over)) :-
    claimant(P), kango_by(C, P), child(C),
    age_nendo_matsu(C, A), A > 1, !.
kettei_status(P, C, decided(oneoff(50000))) :-
    claimant(P), kango_by(C, P), child(C), !.
kettei_status(_, _, error(no_rule_matched)).
