% kita_nyuyoji_teate.pl - kita ward childcare/birth support program
% VERIFIED 2026-06-15. Subject: child. FY-end age 0-2.
% Amount: 5000 JPY (monthly).
% Generated by scripts/gen_ward_kosodate_ouen.py.
% Requires engine.pl.

:- module(kita_nyuyoji_teate, [kettei_status/3, required_fact/3]).

required_fact(_, _, _) :- fail.

kettei_status(P, C, error(structural_facts_missing)) :-
    claimant(P), child(C), \+ age_nendo_matsu(C, _), !.
kettei_status(P, C, ineligible(age_over)) :-
    claimant(P), kango_by(C, P), child(C),
    age_nendo_matsu(C, A), A > 2, !.
kettei_status(P, C, decided(monthly(5000))) :-
    claimant(P), kango_by(C, P), child(C), !.
kettei_status(_, _, error(no_rule_matched)).
