"""Generate ward single-parent housing allowances.

Conditions: hitorioya + hikazei (as income proxy) + has child.
Monthly amount. Subject: claimant (self).

Run from repo root:  python scripts/gen_ward_hitorioya_jutaku.py
"""
from pathlib import Path
import yaml

REPO = Path(__file__).resolve().parents[1]
SOURCES = REPO / "data" / "ward_hitorioya_jutaku_sources.yaml"
PROGRAMS = REPO / "data" / "programs.yaml"

RULE_TEMPLATE = """\
% {pid}.pl - {ward} ward single-parent housing allowance
% VERIFIED {verified}: {yen} JPY/month. hitorioya + hikazei.
% Subject: claimant. Must have child.
% Generated by scripts/gen_ward_hitorioya_jutaku.py.
% Requires engine.pl.

:- module({pid}, [kettei_status/3, required_fact/3]).

:- discontiguous kettei_status/3.
:- discontiguous required_fact/3.

has_child(P) :- claimant(P), kango_by(C, P), child(C), !.

required_fact(P, hitorioya, "single parent") :-
    claimant(P), unknown(hitorioya(P)).
required_fact(P, hikazei, "non-taxable") :-
    claimant(P), unknown(hikazei(P)).

kettei_status(P, self, ineligible(no_child)) :-
    claimant(P), \\+ has_child(P), !.
kettei_status(P, self, ineligible(not_single_parent)) :-
    claimant(P), no(hitorioya(P)), !.
kettei_status(P, self, ineligible(not_low_income)) :-
    claimant(P), no(hikazei(P)), !.
kettei_status(P, self, blocked(Missing)) :-
    claimant(P),
    findall(F, required_fact(P, F, _), Ms), sort(Ms, Missing),
    Missing \\= [], !.
kettei_status(P, self, decided(monthly({yen}))) :-
    claimant(P), yes(hitorioya(P)), yes(hikazei(P)), !.
kettei_status(_, _, error(no_rule_matched)).
"""

CASES_TEMPLATE = """\
# {ward} single-parent housing allowance golden cases
# Generated by scripts/gen_ward_hitorioya_jutaku.py

- name: {ward}_jutaku_decided
  as_of: "2026-06-15"
  facts:
    claimant: {{ birth_date: "1985-01-01" }}
    children: [ {{ id: c1, birth_date: "2018-01-01" }} ]
    askable: {{ hitorioya: true, hikazei: true }}
  expect: {{ subject: self, status: decided, detail: "monthly({yen})" }}

- name: {ward}_jutaku_not_hitorioya
  as_of: "2026-06-15"
  facts:
    claimant: {{ birth_date: "1985-01-01" }}
    children: [ {{ id: c1, birth_date: "2018-01-01" }} ]
    askable: {{ hitorioya: false, hikazei: true }}
  expect: {{ subject: self, status: ineligible, detail: "not_single_parent" }}

- name: {ward}_jutaku_not_hikazei
  as_of: "2026-06-15"
  facts:
    claimant: {{ birth_date: "1985-01-01" }}
    children: [ {{ id: c1, birth_date: "2018-01-01" }} ]
    askable: {{ hitorioya: true, hikazei: false }}
  expect: {{ subject: self, status: ineligible, detail: "not_low_income" }}

- name: {ward}_jutaku_blocked
  as_of: "2026-06-15"
  facts:
    claimant: {{ birth_date: "1985-01-01" }}
    children: [ {{ id: c1, birth_date: "2018-01-01" }} ]
    askable: {{}}
  expect: {{ subject: self, status: blocked, detail: "[hikazei,hitorioya]" }}
"""

STATUTE_TEMPLATE = """\
# {ward} single-parent housing allowance -- source fixation

**VERIFIED ({verified})**

Amount: {yen} JPY/month
Conditions: single-parent + non-taxable household + has child
Source: {ref} {url}

Generated by scripts/gen_ward_hitorioya_jutaku.py.
"""

PROGRAM_ENTRY = """
- id: {pid}
  name: ひとり親家庭等住宅手当（{ward}）
  layer: municipal
  municipality: {ward}
  subject: claimant
  unit: per_household
  amount_type: monthly
  potential_amount: {yen}
  status: supported
  statute:
    - {{ ref: "{ref}", url: "{url}" }}
"""


def _write(path, text):
    with path.open("w", encoding="utf-8", newline="\n") as f:
        f.write(text)


def main():
    wards = yaml.safe_load(SOURCES.read_text(encoding="utf-8"))
    existing = {p["id"] for p in
                yaml.safe_load(PROGRAMS.read_text(encoding="utf-8"))}
    appended = []
    for w in wards:
        ward, pid = w["id"], w["pid"]
        rule_dir = REPO / "rules" / "municipal" / ward
        golden_dir = REPO / "tests" / "golden" / pid
        rule_dir.mkdir(parents=True, exist_ok=True)
        golden_dir.mkdir(parents=True, exist_ok=True)

        _write(rule_dir / f"{pid}.pl",
               RULE_TEMPLATE.format(pid=pid, ward=ward, yen=w["yen"],
                                    verified=w["verified"]))
        _write(golden_dir / "cases.yaml",
               CASES_TEMPLATE.format(ward=ward, yen=w["yen"]))
        _write(golden_dir / "statute_source.md",
               STATUTE_TEMPLATE.format(ward=ward, yen=w["yen"],
                                       ref=w["ref"], url=w["url"],
                                       verified=w["verified"]))
        if pid not in existing:
            with PROGRAMS.open("a", encoding="utf-8", newline="\n") as f:
                f.write(PROGRAM_ENTRY.format(pid=pid, ward=ward, yen=w["yen"],
                                             ref=w["ref"], url=w["url"]))
            appended.append(pid)

    print(f"Generated {len(wards)}; appended {len(appended)} to programs.yaml")


if __name__ == "__main__":
    main()
