"""Generate per-ward shinshin-shogaisha-teate artifacts from verified source table.

Pattern: shibuya_shinshin_shogaisha_teate (hand-implemented) as template.
Two-tier amount: grade_a (shintai 1-2, ryoiku) and grade_b (shintai 3).
Seishin certificates not covered (conservative). Age < 65 for new applications.

Run from repo root:  python scripts/gen_ward_shinshin_teate.py
"""
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parents[1]
SOURCES = REPO / "data" / "ward_shinshin_teate_sources.yaml"
PROGRAMS = REPO / "data" / "programs.yaml"

RULE_TEMPLATE = """\
% ============================================================
% {pid}.pl - {ward} ward disability welfare allowance
% VERIFIED {verified}: grade A (shintai 1-2, ryoiku) {yen_a} JPY/month,
% grade B (shintai 3) {yen_b} JPY/month. No income limit. Age < 65.
% Seishin not covered. Subject: claimant (self).
% Generated by scripts/gen_ward_shinshin_teate.py -- do not edit by hand.
% Sources: tests/golden/{pid}/statute_source.md
% Requires engine.pl.
% ============================================================

:- module({pid}, [kettei_status/3, required_fact/3]).

grade_a(shintai_1).
grade_a(shintai_2).
grade_a(ryoiku).
grade_b(shintai_3).

required_fact(P, shogai_techo, "disability certificate") :-
    claimant(P), unknown(shogai_techo(P)).

kettei_status(P, self, error(structural_facts_missing)) :-
    claimant(P), \\+ age(P, _), !.
kettei_status(P, self, ineligible(age_65_or_over)) :-
    claimant(P), age(P, A), A >= 65, !.
kettei_status(P, self, ineligible(grade_not_covered)) :-
    claimant(P), val(shogai_techo(P), G),
    \\+ grade_a(G), \\+ grade_b(G), !.
kettei_status(P, self, blocked(Missing)) :-
    claimant(P),
    findall(F, required_fact(P, F, _), Ms), sort(Ms, Missing),
    Missing \\= [], !.
kettei_status(P, self, decided(monthly({yen_a}))) :-
    claimant(P), val(shogai_techo(P), G), grade_a(G), !.
kettei_status(P, self, decided(monthly({yen_b}))) :-
    claimant(P), val(shogai_techo(P), G), grade_b(G), !.
kettei_status(_, _, error(no_rule_matched)).
"""

CASES_TEMPLATE = """\
# {name_ja}心身障害者福祉手当 golden cases
# Generated by scripts/gen_ward_shinshin_teate.py

- name: {ward}_shinshin_decided_a
  as_of: "2026-06-15"
  facts:
    claimant: {{ birth_date: "1970-01-01" }}
    children: []
    askable: {{ shogai_techo: "shintai_1" }}
  expect: {{ subject: self, status: decided, detail: "monthly({yen_a})" }}

- name: {ward}_shinshin_decided_b
  as_of: "2026-06-15"
  facts:
    claimant: {{ birth_date: "1970-01-01" }}
    children: []
    askable: {{ shogai_techo: "shintai_3" }}
  expect: {{ subject: self, status: decided, detail: "monthly({yen_b})" }}

- name: {ward}_shinshin_ineligible_seishin
  as_of: "2026-06-15"
  facts:
    claimant: {{ birth_date: "1970-01-01" }}
    children: []
    askable: {{ shogai_techo: "seishin_1" }}
  expect: {{ subject: self, status: ineligible, detail: "grade_not_covered" }}

- name: {ward}_shinshin_ineligible_age
  as_of: "2026-06-15"
  facts:
    claimant: {{ birth_date: "1955-01-01" }}
    children: []
    askable: {{ shogai_techo: "shintai_1" }}
  expect: {{ subject: self, status: ineligible, detail: "age_65_or_over" }}

- name: {ward}_shinshin_blocked
  as_of: "2026-06-15"
  facts:
    claimant: {{ birth_date: "1970-01-01" }}
    children: []
    askable: {{}}
  expect: {{ subject: self, status: blocked, detail: "[shogai_techo]" }}
"""

STATUTE_TEMPLATE = """\
# {name_ja}心身障害者福祉手当 -- source fixation

**VERIFIED ({verified})**

| Item | Value |
|---|---|
| Grade A (shintai 1-2, ryoiku) | {yen_a} JPY/month |
| Grade B (shintai 3) | {yen_b} JPY/month |
| Income limit | None |
| Age limit | < 65 (new applications) |
| Seishin | Not covered |

Source: {ref} {url}

Generated by scripts/gen_ward_shinshin_teate.py from data/ward_shinshin_teate_sources.yaml.
"""

PROGRAM_ENTRY = """
- id: {pid}
  name: 心身障害者福祉手当（{name_ja}）
  layer: municipal
  municipality: {ward}
  subject: claimant
  unit: per_household
  amount_type: monthly
  potential_amount: {yen_a}
  status: supported
  statute:
    - {{ ref: "{ref}", url: "{url}" }}
"""


def _write(path: Path, text: str) -> None:
    with path.open("w", encoding="utf-8", newline="\n") as f:
        f.write(text)


def main() -> None:
    wards = yaml.safe_load(SOURCES.read_text(encoding="utf-8"))
    existing = {p["id"] for p in
                yaml.safe_load(PROGRAMS.read_text(encoding="utf-8"))}
    appended = []
    for w in wards:
        ward = w["id"]
        pid = f"{ward}_shinshin_shogaisha_teate"
        rule_dir = REPO / "rules" / "municipal" / ward
        golden_dir = REPO / "tests" / "golden" / pid
        rule_dir.mkdir(parents=True, exist_ok=True)
        golden_dir.mkdir(parents=True, exist_ok=True)

        _write(rule_dir / f"{pid}.pl",
               RULE_TEMPLATE.format(pid=pid, ward=ward,
                                    name_ja=w["name_ja"],
                                    yen_a=w["yen_a"], yen_b=w["yen_b"],
                                    verified=w["verified"]))
        _write(golden_dir / "cases.yaml",
               CASES_TEMPLATE.format(ward=ward, name_ja=w["name_ja"],
                                     yen_a=w["yen_a"], yen_b=w["yen_b"]))
        _write(golden_dir / "statute_source.md",
               STATUTE_TEMPLATE.format(name_ja=w["name_ja"],
                                       yen_a=w["yen_a"], yen_b=w["yen_b"],
                                       ref=w["ref"], url=w["url"],
                                       verified=w["verified"]))
        if pid not in existing:
            with PROGRAMS.open("a", encoding="utf-8", newline="\n") as f:
                f.write(PROGRAM_ENTRY.format(pid=pid, ward=ward,
                                             name_ja=w["name_ja"],
                                             yen_a=w["yen_a"],
                                             ref=w["ref"], url=w["url"]))
            appended.append(pid)

    print(f"Generated {len(wards)} wards; appended {len(appended)} to programs.yaml")


if __name__ == "__main__":
    main()
