"""Generate per-ward shugaku-enjo (school attendance assistance) artifacts.

Pattern: shibuya_shugaku_enjo (hand-implemented) as template.
Eligibility: hikazei (non-taxable) + school-age child (FY-end 6-15).
Amount: approx 15,000 JPY/year (elementary base).

Run from repo root:  python scripts/gen_ward_shugaku_enjo.py
"""
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parents[1]
SOURCES = REPO / "data" / "ward_shugaku_enjo_sources.yaml"
PROGRAMS = REPO / "data" / "programs.yaml"

RULE_TEMPLATE = """\
% {pid}.pl - {ward} ward school attendance assistance
% VERIFIED {verified}: approx {yen} JPY/year. hikazei-based.
% FY-end age 6-15 (elementary/middle school). Subject: child.
% Generated by scripts/gen_ward_shugaku_enjo.py.
% Requires engine.pl.

:- module({pid}, [kettei_status/3, required_fact/3]).

:- discontiguous kettei_status/3.
:- discontiguous required_fact/3.

school_age(C) :-
    child(C), age_nendo_matsu(C, A), A >= 6, A =< 15.

required_fact(P, hikazei, "non-taxable household") :-
    claimant(P), unknown(hikazei(P)).

kettei_status(P, C, error(structural_facts_missing)) :-
    claimant(P), child(C), \\+ age_nendo_matsu(C, _), !.
kettei_status(P, C, ineligible(not_school_age)) :-
    claimant(P), kango_by(C, P), child(C), \\+ school_age(C), !.
kettei_status(P, C, ineligible(not_low_income)) :-
    claimant(P), kango_by(C, P), child(C), no(hikazei(P)), !.
kettei_status(P, C, blocked(Missing)) :-
    claimant(P), kango_by(C, P), child(C),
    findall(F, required_fact(P, F, _), Ms), sort(Ms, Missing),
    Missing \\= [], !.
kettei_status(P, C, decided(yearly({yen}))) :-
    claimant(P), kango_by(C, P), child(C), yes(hikazei(P)), !.
kettei_status(_, _, error(no_rule_matched)).
"""

CASES_TEMPLATE = """\
# {ward} shugaku enjo golden cases
# Generated by scripts/gen_ward_shugaku_enjo.py

- name: {ward}_enjo_decided
  as_of: "2026-06-15"
  facts:
    claimant: {{ birth_date: "1985-01-01" }}
    children:
      - {{ id: c1, birth_date: "2017-06-01" }}
    askable: {{ hikazei: true }}
  expect: {{ subject: c1, status: decided, detail: "yearly({yen})" }}

- name: {ward}_enjo_ineligible_income
  as_of: "2026-06-15"
  facts:
    claimant: {{ birth_date: "1985-01-01" }}
    children:
      - {{ id: c1, birth_date: "2017-06-01" }}
    askable: {{ hikazei: false }}
  expect: {{ subject: c1, status: ineligible, detail: "not_low_income" }}

- name: {ward}_enjo_ineligible_age
  as_of: "2026-06-15"
  facts:
    claimant: {{ birth_date: "1985-01-01" }}
    children:
      - {{ id: c1, birth_date: "2022-06-01" }}
    askable: {{ hikazei: true }}
  expect: {{ subject: c1, status: ineligible, detail: "not_school_age" }}

- name: {ward}_enjo_blocked
  as_of: "2026-06-15"
  facts:
    claimant: {{ birth_date: "1985-01-01" }}
    children:
      - {{ id: c1, birth_date: "2017-06-01" }}
    askable: {{}}
  expect: {{ subject: c1, status: blocked, detail: "[hikazei]" }}
"""

STATUTE_TEMPLATE = """\
# {ward} school attendance assistance -- source fixation

**VERIFIED ({verified})**

| Item | Value |
|---|---|
| Amount | approx {yen} JPY/year (school supplies base) |
| Target | Non-taxable household, school-age child (FY-end 6-15) |
| Income test | hikazei (non-taxable) as proxy |

Source: {ref} {url}

Generated by scripts/gen_ward_shugaku_enjo.py.
"""

PROGRAM_ENTRY = """
- id: {pid}
  name: 就学援助（{ward}）
  layer: municipal
  municipality: {ward}
  subject: child
  unit: per_child
  amount_type: yearly
  potential_amount: {yen}
  status: supported
  statute:
    - {{ ref: "{ref}", url: "{url}" }}
"""


def _write(path, text):
    with path.open("w", encoding="utf-8", newline="\n") as f:
        f.write(text)


def main():
    wards = yaml.safe_load(SOURCES.read_text(encoding="utf-8"))
    existing = {p["id"] for p in
                yaml.safe_load(PROGRAMS.read_text(encoding="utf-8"))}
    appended = []
    for w in wards:
        ward = w["id"]
        pid = f"{ward}_shugaku_enjo"
        rule_dir = REPO / "rules" / "municipal" / ward
        golden_dir = REPO / "tests" / "golden" / pid
        rule_dir.mkdir(parents=True, exist_ok=True)
        golden_dir.mkdir(parents=True, exist_ok=True)

        _write(rule_dir / f"{pid}.pl",
               RULE_TEMPLATE.format(pid=pid, ward=ward,
                                    yen=w["yen"], verified=w["verified"]))
        _write(golden_dir / "cases.yaml",
               CASES_TEMPLATE.format(ward=ward, yen=w["yen"]))
        _write(golden_dir / "statute_source.md",
               STATUTE_TEMPLATE.format(ward=ward, yen=w["yen"],
                                       ref=w["ref"], url=w["url"],
                                       verified=w["verified"]))
        if pid not in existing:
            with PROGRAMS.open("a", encoding="utf-8", newline="\n") as f:
                f.write(PROGRAM_ENTRY.format(pid=pid, ward=ward,
                                             yen=w["yen"],
                                             ref=w["ref"], url=w["url"]))
            appended.append(pid)

    print(f"Generated {len(wards)} wards; appended {len(appended)} to programs.yaml")


if __name__ == "__main__":
    main()
