% taito_shugaku_enjo.pl - taito ward school attendance assistance
% Generated by batch script: approx 15000 JPY/year. hikazei-based.
% FY-end age 6-15 (elementary/middle school). Subject: child.
% Generated by scripts/gen_ward_shugaku_enjo.py.
% Requires engine.pl.

:- module(taito_shugaku_enjo, [kettei_status/3, required_fact/3]).

:- discontiguous kettei_status/3.
:- discontiguous required_fact/3.

school_age(C) :-
    child(C), age_nendo_matsu(C, A), A >= 6, A =< 15.

required_fact(P, hikazei, "non-taxable household") :-
    claimant(P), unknown(hikazei(P)).

kettei_status(P, C, error(structural_facts_missing)) :-
    claimant(P), child(C), \+ age_nendo_matsu(C, _), !.
kettei_status(P, C, ineligible(not_school_age)) :-
    claimant(P), kango_by(C, P), child(C), \+ school_age(C), !.
kettei_status(P, C, ineligible(not_low_income)) :-
    claimant(P), kango_by(C, P), child(C), no(hikazei(P)), !.
kettei_status(P, C, blocked(Missing)) :-
    claimant(P), kango_by(C, P), child(C),
    findall(F, required_fact(P, F, _), Ms), sort(Ms, Missing),
    Missing \= [], !.
kettei_status(P, C, decided(yearly(15000))) :-
    claimant(P), kango_by(C, P), child(C), yes(hikazei(P)), !.
kettei_status(_, _, error(no_rule_matched)).
