% taito_shiritsu_youchien_hojo.pl - taito ward private kindergarten subsidy
% Generated by batch script: approx 62000 JPY/year. FY-end age 3-5.
% No income limit (most wards). Subject: child.
% Generated by scripts/gen_all_remaining.py.
% Requires engine.pl.

:- module(taito_shiritsu_youchien_hojo, [kettei_status/3, required_fact/3]).

required_fact(_, _, _) :- fail.

kettei_status(P, C, error(structural_facts_missing)) :-
    claimant(P), child(C), \+ age_nendo_matsu(C, _), !.
kettei_status(P, C, ineligible(not_target_age)) :-
    claimant(P), kango_by(C, P), child(C),
    age_nendo_matsu(C, A), (A < 3 ; A > 5), !.
kettei_status(P, C, decided(kubun(youchien_hojo))) :-
    claimant(P), kango_by(C, P), child(C), !.
kettei_status(_, _, error(no_rule_matched)).
