% bunkyo_koukousei_ikusei_shienkin.pl - bunkyo ward childcare/birth support program
% Generated by batch script. Subject: child. FY-end age 16-18.
% Amount: 50000 JPY (yearly).
% Generated by scripts/gen_ward_kosodate_ouen.py.
% Requires engine.pl.

:- module(bunkyo_koukousei_ikusei_shienkin, [kettei_status/3, required_fact/3]).

required_fact(_, _, _) :- fail.

kettei_status(P, C, error(structural_facts_missing)) :-
    claimant(P), child(C), \+ age_nendo_matsu(C, _), !.
kettei_status(P, C, ineligible(not_target_age)) :-
    claimant(P), kango_by(C, P), child(C),
    age_nendo_matsu(C, A), (A < 16 ; A > 18), !.
kettei_status(P, C, decided(yearly(50000))) :-
    claimant(P), kango_by(C, P), child(C), !.
kettei_status(_, _, error(no_rule_matched)).
