"""facts JSON -> Prolog facts text. Deterministic, no LLM.

Implements the mapping layer of docs/specs/architecture.md:
- structural facts (claimant/child/kango_by/seikei_futan/age/age_nendo_matsu)
  are always emitted; kango_by and seikei_futan are form defaults
- askable values become known/2 assertions; null and "declined" emit nothing
  (both are unknown to Prolog; only question selection distinguishes them)
- dates are computed against as_of (JST calendar date passed in by caller)
"""
from __future__ import annotations

from datetime import date

CLAIMANT = "p1"

# askable key -> (predicate, scope). Household-level flat namespace:
# per-child predicates get the same value injected for every child.
ASKABLE_MAP = {
    "nenshu": ("income", "claimant"),  # PLACEHOLDER - VERIFY: v0 passes nenshu
    # through as shotoku. Replace with per-program deduction formulas when
    # official figures are fixed (update golden cases in the same commit).
    "hitorioya": ("hitorioya", "claimant"),
    "hitorioya_jiyuu": ("hitorioya_jiyuu", "claimant"),
    "fuyou_ninzu": ("fuyou_ninzu", "claimant"),
    "seikei_douitsu_partner": ("seikei_douitsu_partner", "per_child"),
}


def age_on(birth: date, ref: date) -> int:
    years = ref.year - birth.year
    if (ref.month, ref.day) < (birth.month, birth.day):
        years -= 1
    return years


def fy_end(as_of: date) -> date:
    """End (March 31) of the Japanese fiscal year containing as_of."""
    return date(as_of.year + 1, 3, 31) if as_of.month >= 4 else date(as_of.year, 3, 31)


def _value_term(value) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, list) and len(value) == 2:
        lo, hi = value
        if not (isinstance(lo, int) and isinstance(hi, int) and lo <= hi):
            raise ValueError(f"bad range: {value!r}")
        return f"range({lo},{hi})"
    if isinstance(value, str) and value.replace("_", "").isalnum() and value[0].islower():
        return value  # enum atom (schema-validated upstream)
    raise ValueError(f"unsupported askable value: {value!r}")


def facts_to_prolog(facts: dict, as_of: date) -> str:
    lines = [
        "% generated by factgen.py - do not edit",
        ":- dynamic claimant/1, child/1, kango_by/2, seikei_futan/2, "
        "age/2, age_nendo_matsu/2.",
        f"claimant({CLAIMANT}).",
    ]
    fy = fy_end(as_of)
    child_ids = []
    for i, ch in enumerate(facts.get("children") or [], start=1):
        cid = ch.get("id") or f"c{i}"
        child_ids.append(cid)
        birth = date.fromisoformat(ch["birth_date"])
        lines += [
            f"child({cid}).",
            f"kango_by({cid}, {CLAIMANT}).",
            f"seikei_futan({CLAIMANT}, {cid}).",
            f"age({cid}, {age_on(birth, as_of)}).",
            f"age_nendo_matsu({cid}, {age_on(birth, fy)}).",
        ]
    for key, value in (facts.get("askable") or {}).items():
        if value is None or value == "declined":
            continue
        if key not in ASKABLE_MAP:
            raise ValueError(f"unknown askable key: {key}")
        pred, scope = ASKABLE_MAP[key]
        term = _value_term(value)
        if scope == "claimant":
            lines.append(f":- assertz(known({pred}({CLAIMANT}), {term})).")
        else:
            for cid in child_ids:
                lines.append(f":- assertz(known({pred}({cid}), {term})).")
    return "\n".join(lines) + "\n"
