"""facts JSON -> Prolog facts text. Deterministic, no LLM.

Implements the mapping layer of docs/specs/architecture.md:
- structural facts (claimant/child/kango_by/seikei_futan/age/age_nendo_matsu)
  are always emitted; kango_by and seikei_futan are form defaults
- askable values become known/2 assertions; null and "declined" emit nothing
  (both are unknown to Prolog; only question selection distinguishes them)
- dates are computed against as_of (JST calendar date passed in by caller)
"""
from __future__ import annotations

import re
from datetime import date

CLAIMANT = "p1"

_SAFE_ATOM = re.compile(r"^[a-z][a-z0-9_]*$")


def _validate_atom(s: str) -> str:
    if not _SAFE_ATOM.match(s):
        raise ValueError(f"invalid identifier: {s!r}")
    return s

# askable key -> (predicate, scope). Household-level flat namespace:
# per-child predicates get the same value injected for every child.
ASKABLE_MAP = {
    # v1 (implemented)
    "nenshu": ("income", "claimant"),
    "shotoku_exact": ("income", "claimant"),
    "hitorioya": ("hitorioya", "claimant"),
    "hitorioya_jiyuu": ("hitorioya_jiyuu", "claimant"),
    "fuyou_ninzu": ("fuyou_ninzu", "claimant"),
    "seikei_douitsu_partner": ("seikei_douitsu_partner", "per_child"),
    "kenkou_hoken": ("kenkou_hoken", "claimant"),
    # v2 (architecture.md § facts JSON)
    "shogai_techo": ("shogai_techo", "claimant"),
    "shogai_teido": ("shogai_teido", "claimant"),
    "kaigo_nintei": ("kaigo_nintei", "claimant"),
    "ninshin": ("ninshin", "claimant"),
    "shussan_yoteibi": ("shussan_yoteibi", "claimant"),
    "juutaku_type": ("juutaku_type", "claimant"),
    "hikazei": ("hikazei", "claimant"),
    "koyou_hoken": ("koyou_hoken", "claimant"),
    "rishoku": ("rishoku", "claimant"),
    "rishoku_jiyuu": ("rishoku_jiyuu", "claimant"),
    "seikatsu_hogo": ("seikatsu_hogo", "claimant"),
    "nanbyo_nintei": ("nanbyo_nintei", "claimant"),
    "jido_yougo_shisetsu": ("jido_yougo_shisetsu", "per_child"),
    "hoken_shubetsu": ("hoken_shubetsu", "claimant"),
    "byouki_kyugyou": ("byouki_kyugyou", "claimant"),
}

# Per-child askables (children[].askable): facts that genuinely differ per
# child (e.g. school enrollment); household-level injection would be wrong.
CHILD_ASKABLE_PREDS = {"koukou_zaigaku", "gakkou_kubun", "shogai_techo_child"}


def age_on(birth: date, ref: date) -> int:
    years = ref.year - birth.year
    if (ref.month, ref.day) < (birth.month, birth.day):
        years -= 1
    return years


def fy_end(as_of: date) -> date:
    """End (March 31) of the Japanese fiscal year containing as_of."""
    return date(as_of.year + 1, 3, 31) if as_of.month >= 4 else date(as_of.year, 3, 31)


def birth_fy(birth: date) -> int:
    """Japanese fiscal year a date falls in (Apr-Mar)."""
    return birth.year if birth.month >= 4 else birth.year - 1


def salary_to_shotoku(nenshu: int) -> int:
    """Salary income deduction, 2020-onward brackets (kyuuyo shotoku koujo).

    Rough FIRST-PASS estimate for the hybrid income design: ignores the
    statutory rounding table, child-support add-in and other deductions.
    Monotonic non-decreasing, so range endpoints convert independently.
    If the converted value straddles a limit, the interview asks for the
    exact post-deduction income (shotoku_exact), which bypasses this."""
    if nenshu <= 1_625_000:
        d = 550_000
    elif nenshu <= 1_800_000:
        d = int(nenshu * 0.4) - 100_000
    elif nenshu <= 3_600_000:
        d = int(nenshu * 0.3) + 80_000
    elif nenshu <= 6_600_000:
        d = int(nenshu * 0.2) + 440_000
    elif nenshu <= 8_500_000:
        d = int(nenshu * 0.1) + 1_100_000
    else:
        d = 1_950_000
    return max(0, nenshu - d)


def _value_term(value) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, list) and len(value) == 2:
        lo, hi = value
        if not (isinstance(lo, int) and isinstance(hi, int) and lo <= hi):
            raise ValueError(f"bad range: {value!r}")
        return f"range({lo},{hi})"
    if isinstance(value, str) and value.replace("_", "").isalnum() and value[0].islower():
        return value  # enum atom (schema-validated upstream)
    raise ValueError(f"unsupported askable value: {value!r}")


MAX_CHILDREN = 20


def facts_to_prolog(facts: dict, as_of: date) -> str:
    children = facts.get("children") or []
    if len(children) > MAX_CHILDREN:
        raise ValueError(f"too many children (max {MAX_CHILDREN})")
    lines = [
        "% generated by factgen.py - do not edit",
        ":- dynamic claimant/1, child/1, kango_by/2, seikei_futan/2, "
        "age/2, age_nendo_matsu/2, birth_nendo/2.",
        f"claimant({CLAIMANT}).",
    ]
    fy = fy_end(as_of)
    claimant_bd = (facts.get("claimant") or {}).get("birth_date")
    if claimant_bd:
        cb = date.fromisoformat(claimant_bd)
        lines += [
            f"age({CLAIMANT}, {age_on(cb, as_of)}).",
            f"age_nendo_matsu({CLAIMANT}, {age_on(cb, fy)}).",
        ]
    child_ids = []
    for i, ch in enumerate(children, start=1):
        raw_id = ch.get("id")
        cid = _validate_atom(raw_id) if raw_id else f"c{i}"
        child_ids.append(cid)
        birth = date.fromisoformat(ch["birth_date"])
        lines += [
            f"child({cid}).",
            f"kango_by({cid}, {CLAIMANT}).",
            f"seikei_futan({CLAIMANT}, {cid}).",
            f"age({cid}, {age_on(birth, as_of)}).",
            f"age_nendo_matsu({cid}, {age_on(birth, fy)}).",
            f"birth_nendo({cid}, {birth_fy(birth)}).",
        ]
        for key, value in (ch.get("askable") or {}).items():
            if key not in CHILD_ASKABLE_PREDS:
                raise ValueError(f"unknown per-child askable key: {key}")
            if value is None or value == "declined":
                continue
            lines.append(f":- assertz(known({key}({cid}), {_value_term(value)})).")
    askable = facts.get("askable") or {}
    # Absent keys are treated exactly as null (unknown) here; rejecting
    # absence is the API layer's job (schema normalization, architecture.md)
    skip = set()
    shotoku = askable.get("shotoku_exact")
    if shotoku is not None and shotoku != "declined":
        skip.add("nenshu")  # exact post-deduction income wins (hybrid design)
    for key, value in askable.items():
        if key in skip or value is None or value == "declined":
            continue
        if key not in ASKABLE_MAP:
            raise ValueError(f"unknown askable key: {key}")
        if key == "nenshu":
            if isinstance(value, list) and len(value) == 2:
                value = [salary_to_shotoku(value[0]), salary_to_shotoku(value[1])]
            elif isinstance(value, int) and not isinstance(value, bool):
                value = salary_to_shotoku(value)
        pred, scope = ASKABLE_MAP[key]
        term = _value_term(value)
        if scope == "claimant":
            lines.append(f":- assertz(known({pred}({CLAIMANT}), {term})).")
        else:
            for cid in child_ids:
                lines.append(f":- assertz(known({pred}({cid}), {term})).")
    return "\n".join(lines) + "\n"
