% minato_shussan_hiyou_josei.pl - minato ward childcare/birth support program
% Generated by batch script. Subject: claimant. Amount: 730000 JPY (oneoff).
% Generated by scripts/gen_ward_kosodate_ouen.py.
% Requires engine.pl.

:- module(minato_shussan_hiyou_josei, [kettei_status/3, required_fact/3]).

required_fact(P, ninshin, "pregnancy") :-
    claimant(P), unknown(ninshin(P)).

kettei_status(P, self, ineligible(not_pregnant)) :-
    claimant(P), no(ninshin(P)), !.
kettei_status(P, self, blocked(Missing)) :-
    claimant(P),
    findall(F, required_fact(P, F, _), Ms), sort(Ms, Missing),
    Missing \= [], !.
kettei_status(P, self, decided(oneoff(730000))) :-
    claimant(P), yes(ninshin(P)), !.
kettei_status(_, _, error(no_rule_matched)).
