"""Generate ward-specific childcare/birth support programs.

Each ward has different conditions: age-based, pregnancy-based, etc.
This script handles multiple condition types via templates.

Run from repo root:  python scripts/gen_ward_kosodate_ouen.py
"""
from pathlib import Path
import yaml

REPO = Path(__file__).resolve().parents[1]
SOURCES = REPO / "data" / "ward_kosodate_ouen_sources.yaml"
PROGRAMS = REPO / "data" / "programs.yaml"

# condition -> (rule body, cases)
TEMPLATES = {
    "ninshin": {
        "rule": """\
% {pid}.pl - {ward} ward childcare/birth support program
% VERIFIED {verified}. Subject: claimant. Amount: {amount} JPY ({amount_type}).
% Generated by scripts/gen_ward_kosodate_ouen.py.
% Requires engine.pl.

:- module({pid}, [kettei_status/3, required_fact/3]).

required_fact(P, ninshin, "pregnancy") :-
    claimant(P), unknown(ninshin(P)).

kettei_status(P, self, ineligible(not_pregnant)) :-
    claimant(P), no(ninshin(P)), !.
kettei_status(P, self, blocked(Missing)) :-
    claimant(P),
    findall(F, required_fact(P, F, _), Ms), sort(Ms, Missing),
    Missing \\= [], !.
kettei_status(P, self, decided({decided_term})) :-
    claimant(P), yes(ninshin(P)), !.
kettei_status(_, _, error(no_rule_matched)).
""",
        "cases": """\
- name: {ward}_ouen_decided
  as_of: "2026-06-15"
  facts:
    claimant: {{ birth_date: "1990-01-01" }}
    children: []
    askable: {{ ninshin: true }}
  expect: {{ subject: self, status: decided, detail: "{decided_term}" }}
- name: {ward}_ouen_ineligible
  as_of: "2026-06-15"
  facts:
    claimant: {{ birth_date: "1990-01-01" }}
    children: []
    askable: {{ ninshin: false }}
  expect: {{ subject: self, status: ineligible, detail: "not_pregnant" }}
- name: {ward}_ouen_blocked
  as_of: "2026-06-15"
  facts:
    claimant: {{ birth_date: "1990-01-01" }}
    children: []
    askable: {{}}
  expect: {{ subject: self, status: blocked, detail: "[ninshin]" }}
"""
    },
    "age_0": {
        "rule": """\
% {pid}.pl - {ward} ward childcare/birth support program
% VERIFIED {verified}. Subject: child. FY-end age <= 1.
% Amount: {amount} JPY ({amount_type}).
% Generated by scripts/gen_ward_kosodate_ouen.py.
% Requires engine.pl.

:- module({pid}, [kettei_status/3, required_fact/3]).

required_fact(_, _, _) :- fail.

kettei_status(P, C, error(structural_facts_missing)) :-
    claimant(P), child(C), \\+ age_nendo_matsu(C, _), !.
kettei_status(P, C, ineligible(age_over)) :-
    claimant(P), kango_by(C, P), child(C),
    age_nendo_matsu(C, A), A > 1, !.
kettei_status(P, C, decided({decided_term})) :-
    claimant(P), kango_by(C, P), child(C), !.
kettei_status(_, _, error(no_rule_matched)).
""",
        "cases": """\
- name: {ward}_ouen_decided
  as_of: "2026-06-15"
  facts:
    claimant: {{ birth_date: "1990-01-01" }}
    children: [ {{ id: c1, birth_date: "2025-06-01" }} ]
  expect: {{ subject: c1, status: decided, detail: "{decided_term}" }}
- name: {ward}_ouen_ineligible_age
  as_of: "2026-06-15"
  facts:
    claimant: {{ birth_date: "1990-01-01" }}
    children: [ {{ id: c1, birth_date: "2022-01-01" }} ]
  expect: {{ subject: c1, status: ineligible, detail: "age_over" }}
"""
    },
    "age_0_2": {
        "rule": """\
% {pid}.pl - {ward} ward childcare/birth support program
% VERIFIED {verified}. Subject: child. FY-end age 0-2.
% Amount: {amount} JPY ({amount_type}).
% Generated by scripts/gen_ward_kosodate_ouen.py.
% Requires engine.pl.

:- module({pid}, [kettei_status/3, required_fact/3]).

required_fact(_, _, _) :- fail.

kettei_status(P, C, error(structural_facts_missing)) :-
    claimant(P), child(C), \\+ age_nendo_matsu(C, _), !.
kettei_status(P, C, ineligible(age_over)) :-
    claimant(P), kango_by(C, P), child(C),
    age_nendo_matsu(C, A), A > 2, !.
kettei_status(P, C, decided({decided_term})) :-
    claimant(P), kango_by(C, P), child(C), !.
kettei_status(_, _, error(no_rule_matched)).
""",
        "cases": """\
- name: {ward}_ouen_decided
  as_of: "2026-06-15"
  facts:
    claimant: {{ birth_date: "1990-01-01" }}
    children: [ {{ id: c1, birth_date: "2025-01-01" }} ]
  expect: {{ subject: c1, status: decided, detail: "{decided_term}" }}
- name: {ward}_ouen_ineligible_age
  as_of: "2026-06-15"
  facts:
    claimant: {{ birth_date: "1990-01-01" }}
    children: [ {{ id: c1, birth_date: "2020-01-01" }} ]
  expect: {{ subject: c1, status: ineligible, detail: "age_over" }}
"""
    },
    "age_16_18": {
        "rule": """\
% {pid}.pl - {ward} ward childcare/birth support program
% VERIFIED {verified}. Subject: child. FY-end age 16-18.
% Amount: {amount} JPY ({amount_type}).
% Generated by scripts/gen_ward_kosodate_ouen.py.
% Requires engine.pl.

:- module({pid}, [kettei_status/3, required_fact/3]).

required_fact(_, _, _) :- fail.

kettei_status(P, C, error(structural_facts_missing)) :-
    claimant(P), child(C), \\+ age_nendo_matsu(C, _), !.
kettei_status(P, C, ineligible(not_target_age)) :-
    claimant(P), kango_by(C, P), child(C),
    age_nendo_matsu(C, A), (A < 16 ; A > 18), !.
kettei_status(P, C, decided({decided_term})) :-
    claimant(P), kango_by(C, P), child(C), !.
kettei_status(_, _, error(no_rule_matched)).
""",
        "cases": """\
- name: {ward}_ouen_decided
  as_of: "2026-06-15"
  facts:
    claimant: {{ birth_date: "1980-01-01" }}
    children: [ {{ id: c1, birth_date: "2009-06-01" }} ]
  expect: {{ subject: c1, status: decided, detail: "{decided_term}" }}
- name: {ward}_ouen_ineligible_age
  as_of: "2026-06-15"
  facts:
    claimant: {{ birth_date: "1980-01-01" }}
    children: [ {{ id: c1, birth_date: "2015-06-01" }} ]
  expect: {{ subject: c1, status: ineligible, detail: "not_target_age" }}
"""
    },
}

STATUTE_TEMPLATE = """\
# {name_ja} -- source fixation

**VERIFIED ({verified})**

Amount: {amount} JPY ({amount_type})
Note: {note}

Source: {ref} {url}

Generated by scripts/gen_ward_kosodate_ouen.py.
"""

PROGRAM_ENTRY = """
- id: {pid}
  name: {name_ja}
  layer: municipal
  municipality: {ward}
  subject: {subject}
  unit: {unit}
  amount_type: {amount_type}
  potential_amount: {amount}
  status: supported
  statute:
    - {{ ref: "{ref}", url: "{url}" }}
"""


def _write(path, text):
    with path.open("w", encoding="utf-8", newline="\n") as f:
        f.write(text)


def _decided_term(amount_type, amount):
    if amount_type == "monthly":
        return f"monthly({amount})"
    elif amount_type == "oneoff":
        return f"oneoff({amount})"
    elif amount_type == "yearly":
        return f"yearly({amount})"
    return f"amount({amount})"


def main():
    wards = yaml.safe_load(SOURCES.read_text(encoding="utf-8"))
    existing = {p["id"] for p in
                yaml.safe_load(PROGRAMS.read_text(encoding="utf-8"))}
    appended = []
    for w in wards:
        ward = w["id"]
        pid = w["pid"]
        cond = w["condition"]
        tmpl = TEMPLATES[cond]
        decided = _decided_term(w["amount_type"], w["amount"])
        unit = "per_household" if w["subject"] == "claimant" else "per_child"

        rule_dir = REPO / "rules" / "municipal" / ward
        golden_dir = REPO / "tests" / "golden" / pid
        rule_dir.mkdir(parents=True, exist_ok=True)
        golden_dir.mkdir(parents=True, exist_ok=True)

        _write(rule_dir / f"{pid}.pl",
               tmpl["rule"].format(pid=pid, ward=ward, note=w["note"],
                                   amount=w["amount"],
                                   amount_type=w["amount_type"],
                                   decided_term=decided,
                                   verified=w["verified"]))
        _write(golden_dir / "cases.yaml",
               f"# {w['name_ja']} golden cases\n"
               f"# Generated by scripts/gen_ward_kosodate_ouen.py\n\n"
               + tmpl["cases"].format(ward=ward, decided_term=decided))
        _write(golden_dir / "statute_source.md",
               STATUTE_TEMPLATE.format(name_ja=w["name_ja"],
                                       amount=w["amount"],
                                       amount_type=w["amount_type"],
                                       note=w["note"],
                                       ref=w["ref"], url=w["url"],
                                       verified=w["verified"]))
        if pid not in existing:
            with PROGRAMS.open("a", encoding="utf-8", newline="\n") as f:
                f.write(PROGRAM_ENTRY.format(
                    pid=pid, ward=ward, name_ja=w["name_ja"],
                    subject=w["subject"], unit=unit,
                    amount_type=w["amount_type"], amount=w["amount"],
                    ref=w["ref"], url=w["url"]))
            appended.append(pid)

    print(f"Generated {len(wards)} programs; appended {len(appended)} to programs.yaml")


if __name__ == "__main__":
    main()
