% ota_hitorioya_jutaku.pl - ota ward single-parent housing allowance
% Generated by batch script: 15000 JPY/month. hitorioya + hikazei.
% Subject: claimant. Must have child.
% Generated by scripts/gen_ward_hitorioya_jutaku.py.
% Requires engine.pl.

:- module(ota_hitorioya_jutaku, [kettei_status/3, required_fact/3]).

:- discontiguous kettei_status/3.
:- discontiguous required_fact/3.

has_child(P) :- claimant(P), kango_by(C, P), child(C), !.

required_fact(P, hitorioya, "single parent") :-
    claimant(P), unknown(hitorioya(P)).
required_fact(P, hikazei, "non-taxable") :-
    claimant(P), unknown(hikazei(P)).

kettei_status(P, self, ineligible(no_child)) :-
    claimant(P), \+ has_child(P), !.
kettei_status(P, self, ineligible(not_single_parent)) :-
    claimant(P), no(hitorioya(P)), !.
kettei_status(P, self, ineligible(not_low_income)) :-
    claimant(P), no(hikazei(P)), !.
kettei_status(P, self, blocked(Missing)) :-
    claimant(P),
    findall(F, required_fact(P, F, _), Ms), sort(Ms, Missing),
    Missing \= [], !.
kettei_status(P, self, decided(monthly(15000))) :-
    claimant(P), yes(hitorioya(P)), yes(hikazei(P)), !.
kettei_status(_, _, error(no_rule_matched)).
