% ota_ninkagai_hoiku_hojo.pl - ota ward unlicensed daycare subsidy
% Generated by batch script: approx 20000 JPY/month. FY-end age 0-5.
% No income limit for basic subsidy. Subject: child.
% Generated by scripts/gen_all_remaining.py.
% Requires engine.pl.

:- module(ota_ninkagai_hoiku_hojo, [kettei_status/3, required_fact/3]).

required_fact(_, _, _) :- fail.

kettei_status(P, C, error(structural_facts_missing)) :-
    claimant(P), child(C), \+ age_nendo_matsu(C, _), !.
kettei_status(P, C, ineligible(not_target_age)) :-
    claimant(P), kango_by(C, P), child(C),
    age_nendo_matsu(C, A), A > 5, !.
kettei_status(P, C, decided(kubun(ninkagai_hojo))) :-
    claimant(P), kango_by(C, P), child(C), !.
kettei_status(_, _, error(no_rule_matched)).
